### ISSUE TITLE
Missing GPG key 

### ISSUE THREAD

**Issue by yukiman76** [canonical/alertmanager-k8s-operator#190]
### Bug Description

During a juju deployment of the mon stack Grafana does not deploy with error 

### To Reproduce

From documentation on deploying mon stack 

juju deploy charmed-kubernetes --overlay ./logging-egf-overlay.yaml --overlay ./monitoring-pgt-overlay.yaml --overlay ./kubernetes-worker.yaml
juju status

### Environment

on lxd in a maas deployed stack 

### Relevant log output

```shell
2023-09-11 20:39:45 INFO juju.worker.uniter resolver.go:155 awaiting error resolution for "install" hook
2023-09-11 20:43:05 INFO juju.worker.uniter resolver.go:155 awaiting error resolution for "install" hook
2023-09-11 20:44:45 INFO juju.worker.uniter resolver.go:155 awaiting error resolution for "install" hook
2023-09-11 20:44:46 ERROR unit.grafana/0.juju-log server.go:316 Unable to find implementation for relation: requires of register-application
2023-09-11 20:44:55 WARNING unit.grafana/0.install logger.go:60 W: GPG error: https://packages.grafana.com/oss/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 963FA27710458545
2023-09-11 20:44:55 WARNING unit.grafana/0.install logger.go:60 E: The repository 'https://packages.grafana.com/oss/deb stable InRelease' is not signed.
2023-09-11 20:45:08 WARNING unit.grafana/0.install logger.go:60 W: GPG error: https://packages.grafana.com/oss/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 963FA27710458545
2023-09-11 20:45:08 WARNING unit.grafana/0.install logger.go:60 E: The repository 'https://packages.grafana.com/oss/deb stable InRelease' is not signed.
2023-09-11 20:45:21 WARNING unit.grafana/0.install logger.go:60 W: GPG error: https://packages.grafana.com/oss/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 963FA27710458545
2023-09-11 20:45:21 WARNING unit.grafana/0.install logger.go:60 E: The repository 'https://packages.grafana.com/oss/deb stable InRelease' is not signed.
2023-09-11 20:45:34 WARNING unit.grafana/0.install logger.go:60 W: GPG error: https://packages.grafana.com/oss/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 963FA27710458545
2023-09-11 20:45:34 WARNING unit.grafana/0.install logger.go:60 E: The repository 'https://packages.grafana.com/oss/deb stable InRelease' is not signed.
2023-09-11 20:45:48 WARNING unit.grafana/0.install logger.go:60 W: GPG error: https://packages.grafana.com/oss/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 963FA27710458545
2023-09-11 20:45:48 WARNING unit.grafana/0.install logger.go:60 E: The repository 'https://packages.grafana.com/oss/deb stable InRelease' is not signed.
2023-09-11 20:46:01 WARNING unit.grafana/0.install logger.go:60 W: GPG error: https://packages.grafana.com/oss/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 963FA27710458545
2023-09-11 20:46:01 WARNING unit.grafana/0.install logger.go:60 E: The repository 'https://packages.grafana.com/oss/deb stable InRelease' is not signed.
2023-09-11 20:46:14 WARNING unit.grafana/0.install logger.go:60 W: GPG error: https://packages.grafana.com/oss/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 963FA27710458545
2023-09-11 20:46:14 WARNING unit.grafana/0.install logger.go:60 E: The repository 'https://packages.grafana.com/oss/deb stable InRelease' is not signed.
2023-09-11 20:46:27 WARNING unit.grafana/0.install logger.go:60 W: GPG error: https://packages.grafana.com/oss/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 963FA27710458545
2023-09-11 20:46:27 WARNING unit.grafana/0.install logger.go:60 E: The repository 'https://packages.grafana.com/oss/deb stable InRelease' is not signed.
2023-09-11 20:46:40 WARNING unit.grafana/0.install logger.go:60 W: GPG error: https://packages.grafana.com/oss/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 963FA27710458545
2023-09-11 20:46:40 WARNING unit.grafana/0.install logger.go:60 E: The repository 'https://packages.grafana.com/oss/deb stable InRelease' is not signed.
2023-09-11 20:46:54 WARNING unit.grafana/0.install logger.go:60 W: GPG error: https://packages.grafana.com/oss/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 963FA27710458545
2023-09-11 20:46:54 WARNING unit.grafana/0.install logger.go:60 E: The repository 'https://packages.grafana.com/oss/deb stable InRelease' is not signed.
2023-09-11 20:47:07 WARNING unit.grafana/0.install logger.go:60 W: GPG error: https://packages.grafana.com/oss/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 963FA27710458545
2023-09-11 20:47:07 WARNING unit.grafana/0.install logger.go:60 E: The repository 'https://packages.grafana.com/oss/deb stable InRelease' is not signed.
2023-09-11 20:47:20 WARNING unit.grafana/0.install logger.go:60 W: GPG error: https://packages.grafana.com/oss/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 963FA27710458545
2023-09-11 20:47:20 WARNING unit.grafana/0.install logger.go:60 E: The repository 'https://packages.grafana.com/oss/deb stable InRelease' is not signed.
2023-09-11 20:47:20 ERROR unit.grafana/0.juju-log server.go:316 Hook error:
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['apt-get', 'update']' returned non-zero exit status 100.
2023-09-11 20:47:20 WARNING unit.grafana/0.install logger.go:60 Traceback (most recent call last):
2023-09-11 20:47:20 WARNING unit.grafana/0.install logger.go:60   File "/var/lib/juju/agents/unit-grafana-0/charm/hooks/install", line 22, in <module>
2023-09-11 20:47:20 WARNING unit.grafana/0.install logger.go:60     main()
2023-09-11 20:47:20 WARNING unit.grafana/0.install logger.go:60   File "/var/lib/juju/agents/unit-grafana-0/.venv/lib/python3.8/site-packages/charms/reactive/__init__.py", line 74, in main
2023-09-11 20:47:20 WARNING unit.grafana/0.install logger.go:60     bus.dispatch(restricted=restricted_mode)
2023-09-11 20:47:20 WARNING unit.grafana/0.install logger.go:60   File "/var/lib/juju/agents/unit-grafana-0/.venv/lib/python3.8/site-packages/charms/reactive/bus.py", line 390, in dispatch
2023-09-11 20:47:20 WARNING unit.grafana/0.install logger.go:60     _invoke(other_handlers)
2023-09-11 20:47:20 WARNING unit.grafana/0.install logger.go:60   File "/var/lib/juju/agents/unit-grafana-0/.venv/lib/python3.8/site-packages/charms/reactive/bus.py", line 359, in _invoke
2023-09-11 20:47:20 WARNING unit.grafana/0.install logger.go:60     handler.invoke()
2023-09-11 20:47:20 WARNING unit.grafana/0.install logger.go:60   File "/var/lib/juju/agents/unit-grafana-0/.venv/lib/python3.8/site-packages/charms/reactive/bus.py", line 181, in invoke
2023-09-11 20:47:20 WARNING unit.grafana/0.install logger.go:60     self._action(*args)
2023-09-11 20:47:20 WARNING unit.grafana/0.install logger.go:60   File "/var/lib/juju/agents/unit-grafana-0/charm/reactive/grafana.py", line 260, in install_packages
2023-09-11 20:47:20 WARNING unit.grafana/0.install logger.go:60     fetch.configure_sources(update=True)
2023-09-11 20:47:20 WARNING unit.grafana/0.install logger.go:60   File "/var/lib/juju/agents/unit-grafana-0/.venv/lib/python3.8/site-packages/charmhelpers/fetch/__init__.py", line 149, in configure_sources
2023-09-11 20:47:20 WARNING unit.grafana/0.install logger.go:60     _fetch_update(fatal=True)
2023-09-11 20:47:20 WARNING unit.grafana/0.install logger.go:60   File "/var/lib/juju/agents/unit-grafana-0/.venv/lib/python3.8/site-packages/charmhelpers/fetch/ubuntu.py", line 400, in apt_update
2023-09-11 20:47:20 WARNING unit.grafana/0.install logger.go:60     _run_apt_command(cmd, fatal)
2023-09-11 20:47:20 WARNING unit.grafana/0.install logger.go:60   File "/var/lib/juju/agents/unit-grafana-0/.venv/lib/python3.8/site-packages/charmhelpers/fetch/ubuntu.py", line 945, in _run_apt_command
2023-09-11 20:47:20 WARNING unit.grafana/0.install logger.go:60     _run_with_retries(
2023-09-11 20:47:20 WARNING unit.grafana/0.install logger.go:60   File "/var/lib/juju/agents/unit-grafana-0/.venv/lib/python3.8/site-packages/charmhelpers/fetch/ubuntu.py", line 922, in _run_with_retries
2023-09-11 20:47:20 WARNING unit.grafana/0.install logger.go:60     result = subprocess.check_call(cmd, env=env, **kwargs)
2023-09-11 20:47:20 WARNING unit.grafana/0.install logger.go:60   File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
2023-09-11 20:47:20 WARNING unit.grafana/0.install logger.go:60     raise CalledProcessError(retcode, cmd)
2023-09-11 20:47:20 WARNING unit.grafana/0.install logger.go:60 subprocess.CalledProcessError: Command '['apt-get', 'update']' returned non-zero exit status 100.
2023-09-11 20:47:20 ERROR juju.worker.uniter.operation runhook.go:153 hook "install" (via explicit, bespoke hook script) failed: exit status 1
2023-09-11 20:47:20 INFO juju.worker.uniter resolver.go:155 awaiting error resolution for "install" hook
2023-09-11 20:48:34 INFO juju.worker.uniter resolver.go:155 awaiting error resolution for "install" hook
2023-09-11 20:52:20 INFO juju.worker.uniter resolver.go:155 awaiting error resolution for "install" hook

which repeats
```

### Additional context

Correct with 
wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -
followed by a 
sudo apt-get update

then juju took over and installed the needed parts and the rest of the env came up

**Comment by sed-i** [comment]
Thanks @yukiman76!
I see the log mentions `charmhelpers`. I guess this issue belongs to one of the (grafana?) machine charms:
- https://launchpad.net/charm-grafana
- https://launchpad.net/charm-prometheus-alertmanager
